### ISSUE TITLE
chore: switch to Jasmine

### ISSUE THREAD

**Issue by lilsweetcaligula** [OpenPromisesProject/op-serverless-api#134]
I was wrong to not follow your advice at the time, @nazreen. Jasmine will suit the project a lot better than Mocha - Jasmine is a good "batteries included" package with all the necessary tools for the kind of testing we need to do.

I would like to suggest we switch to Jasmine.

**Comment by nazreen** [comment]
I have not touched the tests at all to be honest. and I have not used mocha personally, only jasmine (and I am happy with it). between mocha and jasmine I am also more familiar with jasmine so I can more easily work on it if it's jasmine.

**Comment by nazreen** [comment]
I also don't remember giving any advice on which test runner to pick!

**Comment by lilsweetcaligula** [comment]
> I also don't remember giving any advice on which test runner to pick!

Oh, sorry, must be a false memory, haha.

**Comment by nazreen** [comment]
@lilsweetcaligula this is done right? do close if done :)
