### ISSUE TITLE
docs: add missing steps

### ISSUE THREAD

**Issue by nazreen** [OpenPromisesProject/op-serverless-api#142]
- `npm i`
- `firebase login`

- [ ] make up and running into a proper list
- [ ] login step + how to obtain firebase token
- [ ] on the necessary headers token and email

**Comment by lilsweetcaligula** [comment]
Please see my comments on: https://github.com/OpenPromisesProject/op-serverless-api/pull/143

I tried to describe most of the aforementioned steps.
