### ISSUE TITLE
Port 5001 is not open on localhost, could not start functions emulator.

### ISSUE THREAD

**Issue by nazreen** [OpenPromisesProject/op-serverless-api#147]
when running `npm run serve-h`

**Comment by nazreen** [comment]
https://github.com/firebase/firebase-tools/issues/1605

**Comment by nazreen** [comment]
installing firebase-tools version 7.2.3 does not work as recommended by the above linked thread

**Comment by nazreen** [comment]
installing latest version 7.8.1 does not work either

**Comment by nazreen** [comment]
tried the below:

after version update, run (if Mac):
`sed -i '' 's/stopPort: port/stopPort: port+1/' /usr/local/lib/node_modules/firebase-tools/lib/emulator/controller.js`

make sure it's the right path for the global node_modules by checking `npm root -g`

did not solve

**Comment by nazreen** [comment]
just run in on a different port. 

this issue might have been local to me.

solution: add flag to usual command like so `npm run serve-h -- --port=5003`

**Comment by nazreen** [comment]
@lilsweetcaligula did you ever run into this issue? I just experienced it just now

**Comment by lilsweetcaligula** [comment]
@nazreen The error message looks oddly familiar but I cannot recall the exact circumstances under which I may have seen it. But my guess is - if running on a different port does resolve the problem, then it's probably the problem of a port being occupied - very likely by another instance of Firebase.
