### ISSUE TITLE
a caching layer should exist for READing promises

### ISSUE THREAD

**Issue by doodlesbykumbi** [OpenPromisesProject/op-serverless-api#39]
`GIVEN` a popular route with a set of parameters e.g. `./promises/?live=true&orderBy=source_date&pageSize=10&reverse=true`
`WHEN` this route is hit
`THEN` cached results should be served

Ideally, when there's any mutation to promises then the cache should be invalidated and preemptively calculated :)

**Comment by nxmohamad** [comment]
how would this be implemented? do we need another microservice for this? or another db?

**Comment by doodlesbykumbi** [comment]
same db. normally, caching is done using some key-value store like redis or memcached but not sure how it would work in the serverless world. i'll investigate

**Comment by umarrasydan** [comment]
We should probably have this in FE for now

**Comment by nazreen** [comment]
not priority
