### ISSUE TITLE
require firebaseAuth for createPolitician

### ISSUE THREAD

**Issue by nazreen** [OpenPromisesProject/op-serverless-api#41]

**Comment by lilsweetcaligula** [comment]
@nazreen 

Should the auth be required for `updatePolitician` and `deletePolitician` as well?

**Comment by nazreen** [comment]
@lilsweetcaligula definitely :) this issue was created so long ago. I'm not sure why I specified createPolitician. Maybe I want to go about it via a piecemeal approach
